workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH == "citest"
  
build_files:
  needs: []
  image:
    name: mikefarah/yq:4.18.1
    entrypoint: [""]
  script:
    - cp Build/release.sh /tmp/release.sh
    - chmod +x /tmp/release.sh
    - VERSION="1.$(date +%Y%m%d.%H%M%S)"
    - echo "Version $VERSION"
    - /tmp/release.sh VRCFury.$VERSION.unitypackage Assets/VRCFury/
    - echo "VERSION=$VERSION" > build.env
    - echo "PACKAGE_URL=$CI_JOB_URL/artifacts/raw/VRCFury.$VERSION.unitypackage" >> build.env
  artifacts:
    paths:
      - "*.unitypackage"
    reports:
      dotenv: build.env

release:
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - echo 'running release_job'
  needs:
    - job: build_files
      artifacts: true
  release:
    name: 'VRCFury $VERSION'
    description: This is a release of VRCFury. Click 'Download Unity Package' above to download!
    tag_name: '$VERSION'
    assets:
      links:
        - name: 'Download Unity Package'
          url: '${PACKAGE_URL}'
